### PR TITLE
CSYS-194: Migrate dialogs

### PR DESCRIPTION
**Pull request by lucianoratamero**
Please check and review the `confetti-ds`' counterpart to this PR, since they need to be merged together.

**Related to:** https://github.com/labcodes/confetti-ds/pull/3

**Link to task:** https://labcodes.atlassian.net/browse/CSYS-194

**Staging app:** https://migrate-dialogs--confetti-storybook.netlify.app/

**How to test:**
- open the staging app
- check that the stories for Message and Standard Dialogs are working as intended

**Description of your solution:**
Added stories with custom behavior for Message and Standard Dialogs

### CODE REVIEW

**Comment by CavalcanteLucas** [comment]
I'm having this error both in `MessageDialog` as in `StandardDialog` stories:

image

**Review by CavalcanteLucas — CHANGES_REQUESTED** [review]
I'm having this error both in `MessageDialog` as in `StandardDialog` stories:

image

**Comment by lucianoratamero** [comment]
@CavalcanteLucas , are you sure you were at the correct commit on confetti-ds when validating?
because everything works on the staging app.

**Review by falconedani — APPROVED** [review]
LGTM! 🏆

**Pull request merged**
